---
services:
  front:
    build:
      context: organiz_front
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      VITE_API_BASE_URL: http://127.0.0.1/api/v1
    ports:
      - 80:80
    networks:
      - backend_network
    restart: always
  api:
    build:
      context: organiz_api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_TYPE: postgres
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: api_user
      DATABASE_PASSWORD: password
      DATABASE_NAME: organiz_database
      LOGGING_LEVEL: INFO
      HTTP_LISTENING_PORT: 3000
    ports:
      - 3000:3000
    networks: 
      - data_network
      - backend_network
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:17.2-bookworm
    restart: always
    environment:
      POSTGRES_DB: organiz_database
      POSTGRES_PASSWORD: password
      POSTGRES_USER: api_user
    ports:
      - "5432:5432"
    networks: 
      - data_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  data_network:
  backend_network:
volumes:
  postgres-data:
