---
services:
  api:
    build:
      context: organiz_api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks: 
      - data_network
      - backend_network
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:17.2-bookworm
    restart: always
    environment:
      POSTGRES_DB: organiz_database
      POSTGRES_PASSWORD: password
      POSTGRES_USER: api_user
    ports:
      - "5432:5432"
    networks: 
      - data_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  data_network:
  backend_network:
volumes:
  postgres-data:
